### ISSUE TITLE
there is another little bug I found out.

### ISSUE THREAD

**Issue by nnkn** [markw65/prettier-extension-monkeyc#8]
as showed in pic ,when I use `i+=1;`in an `for` loop, after optimized, it will disappear,but when I changed it to `i++;` ,it works well
I don't know why , what I can do is just submit a new issue =)
![ik7Iby.png](https://i.328888.xyz/2023/03/29/ik7Iby.png)

**Comment by markw65** [comment]
Thanks - I was able to reproduce the problem. I'll let you know what I find.

**Comment by markw65** [comment]
This was a bug with [singleUseCopyProp](https://github.com/markw65/monkeyc-optimizer/wiki/Local-variable-elimination#single-use-copy-propagation) - so you should be able to work around it by turning that off.

Here's a minimal repro.

```
function bug(i) {
  System.println(i);
  i += 1;
  System.println(i);
  i++;
  return i;
}
```
The problem is that the optimizer doesn't see the `i++` as a "use" of i, so it thinks that the result of `i += 1` is only used in one place, and the optimized code ends up as:
```
function bug(i) {
  System.println(i);
  // the optimizer incorrectly thinks the result of i += 1 is only used in one place,
  // and substitutes i+1 in the following line
  System.println(i + 1);
  // here it correctly sees that the result of i++ is only used in one place,
  // and substitutes i+1. But the value of i is wrong because it deleted the first i+=1.
  return i + 1;
}
```
In your example its the `i++` in the for loop causing the same issue (and changing that to `i+=1` fixes it). Note that eventually, the optimizer replaces that `i++` with `i += 1` anyway; but that doesn't happen until its already deleted the other `i += 1`.

I think there's an easy fix - I just have to run tests to make sure it doesn't introduce any new problems.

**Comment by nnkn** [comment]
> This was a bug with [singleUseCopyProp](https://github.com/markw65/monkeyc-optimizer/wiki/Local-variable-elimination#single-use-copy-propagation) - so you should be able to work around it by turning that off.
> 
> Here's a minimal repro.
> 
> ```
> function bug(i) {
>   System.println(i);
>   i += 1;
>   System.println(i);
>   i++;
>   return i;
> }
> ```
> 
> The problem is that the optimizer doesn't see the `i++` as a "use" of i, so it thinks that the result of `i += 1` is only used in one place, and the optimized code ends up as:
> 
> ```
> function bug(i) {
>   System.println(i);
>   // the optimizer incorrectly thinks the result of i += 1 is only used in one place,
>   // and substitutes i+1 in the following line
>   System.println(i + 1);
>   // here it correctly sees that the result of i++ is only used in one place,
>   // and substitutes i+1. But the value of i is wrong because it deleted the first i+=1.
>   return i + 1;
> }
> ```
> 
> In your example its the `i++` in the for loop causing the same issue (and changing that to `i+=1` fixes it). Note that eventually, the optimizer replaces that `i++` with `i += 1` anyway; but that doesn't happen until its already deleted the other `i += 1`.
> 
> I think there's an easy fix - I just have to run tests to make sure it doesn't introduce any new problems.

got it ! thank you !
